# Generated by Django 3.1.7 on 2021-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
